id: P4148D88A
initial_creation_type: input
source_metadata:
  title: Akhyuk Rinpoche Lungtok Gyaltsen
  language: en
  description: 'Texts by Khenpo Akhyuk Rinpoche Drubwang Lungtok Gyaltsen (a khyug
    grub dbang lung rtogs rgyal mtshan, 1927–2011), the renowned successor of Tromge
    Arik Rinpoche at the vast Dharma encampment of Yachen Gar:'
  volume:
    6a2e057846cc4c41aaf37998496f441a:
      title: A Prayer to the Precious Teacher of Incomparable Kindness, Jamyang Lungtok
        Gyaltsen
      parent: Prayers
created_at: '2022-02-28T22:35:55.955801'
last_modified_at: '2022-02-28T22:35:55.955807'
